# Generated by Django 4.1.5 on 2023-01-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=25)),
                ('tipe', models.CharField(max_length=25)),
                ('purchase_price', models.IntegerField()),
                ('purchase_year', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_category', to='inventaris.category')),
            ],
            options={
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenance_date', models.CharField(max_length=20)),
                ('maintenance_vendor', models.CharField(max_length=50)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_inventory', to='inventaris.inventory')),
                ('staff_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_staff', to='inventaris.staff')),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
