# Generated by Django 4.1.5 on 2023-01-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceinventory',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relasi_inventory', to='inventaris.inventory'),
        ),
    ]
