# Generated by Django 4.1.5 on 2023-01-27 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=25)),
                ('tipe', models.CharField(max_length=25)),
                ('purchasePrice', models.IntegerField()),
                ('purchaseYear', models.IntegerField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_category', to='inventaris.category')),
            ],
            options={
                'db_table': 'inventories',
            },
        ),
    ]
