# Generated by Django 4.1.5 on 2023-01-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maintenanceDate', models.IntegerField()),
                ('maintenanceVendor', models.CharField(max_length=50)),
                ('inventoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_inventory', to='inventaris.inventory')),
                ('staffPic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relasi_staff', to='inventaris.staff')),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
