# Generated by Django 4.1.5 on 2023-01-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0004_maintenanceinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceinventory',
            name='maintenanceDate',
            field=models.CharField(max_length=20),
        ),
    ]
