# Generated by Django 4.1.5 on 2023-01-27 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0006_alter_category_id_alter_inventory_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='categoryId',
            new_name='category',
        ),
    ]
